version: 2
jobs:
  build:
    working_directory: ~/blinkist/blinkist-config
    parallelism: 1
    docker:
    - image: cimg/ruby:2.7.3-browsers
    steps:
    - checkout
    - restore_cache:
        keys:
          - gem-cache-{{ checksum "Gemfile.lock" }}
          - gem-cache-
    - run: 
        name: Bundle Install
        command: bundle install --jobs=4 --retry=3 --path=vendor/bundle
    - save_cache:
        key: gem-cache-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
    - run:
        name: RSpec
        command: bundle exec rspec --format progress spec
        environment:
          RAILS_ENV: test
          RACK_ENV: test
